import type { Metadata } from "next";

import {
  Bricolage_Grotesque,
  Encode_Sans_Expanded,
  Inter,
} from "next/font/google";

import "./globals.css";

import SmoothScroll from "@/components/SmoothScroll";
import CustomScrollbar from "@/components/Scrollbar";

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
  display: "swap",
  weight: "700",
});

const encodeSans = Encode_Sans_Expanded({
  variable: "--font-encode",
  subsets: ["latin"],
  display: "swap",
  weight: "600",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Pranay Prasad — Full Stack Developer",
  description:
    "Portfolio of Pranay Prasad, a full stack developer building thoughtful digital experiences.",
};

export default function RootLayout({
  children,
}: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`
        h-full
        antialiased
        ${bricolage.variable}
        ${encodeSans.variable}
        ${inter.variable}
      `}
    >
      <body className="flex min-h-full flex-col">
        <SmoothScroll />
        <CustomScrollbar />
        {children}
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import "./globals.css";
// import {
//   Bricolage_Grotesque,
//   Encode_Sans_Expanded,
//   Inter,
// } from "next/font/google";

// import "./globals.css";
// import SmoothScroll from "@/components/SmoothScroll";
// import CustomScrollbar from "@/components/Scrollbar";

// const bricolage = Bricolage_Grotesque({
//   variable: "--font-bricolage",
//   subsets: ["latin"],
//   display: "swap",
//   weight: "700",
// });

// const encodeSans = Encode_Sans_Expanded({
//   variable: "--font-encode",
//   subsets: ["latin"],
//   display: "swap",
//   weight: "600"
// });

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
//   display: "swap",
// });



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`h-full antialiased ${bricolage.variable} ${encodeSans.variable} ${inter.variable}`}
//     >
//       <body className="flex flex-col">
//         <SmoothScroll />
//         <CustomScrollbar/>
//         {children}
//       </body>
//     </html>
//   );
// }
